// src/components/core/Navbar.tsx
'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';

export default function Navbar() {
  const [isOpen, setIsOpen] = useState(false);
  const [isScrolled, setIsScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY > 30) {
        setIsScrolled(true);
      } else {
        setIsScrolled(false);
      }
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const navLinks = [
    { label: 'Accueil', href: '/' },
    { label: 'Approche & Méthode', href: '/#methode' },
    { label: 'Projets & Solutions', href: '/work' },
    { label: 'À Propos', href: '/about' },
  ];

  return (
    <>
      <header className={`nav-wrapper ${isScrolled ? 'is-scrolled' : ''}`}>
        <div className="nav-container">
          {/* Logo / Brand Name */}
          <Link href="/" className="nav-logo">
            <span className="logo-icon">M</span>
            <div className="logo-text">
              <span className="name">Marie Sylvanus</span>
              <span className="role">AUTOMATISATION · IA</span>
            </div>
          </Link>

          {/* Desktop Nav Links */}
          <nav className="desktop-links">
            {navLinks.map((link) => (
              <Link key={link.label} href={link.href} className="nav-item">
                {link.label}
              </Link>
            ))}
          </nav>

          {/* Action CTA Button */}
          <div className="nav-actions">
            <Link href="/#diagnostic" className="cta-diagnostic-btn">
              <span className="cta-dot" />
              <span>Diagnostic 15 min</span>
            </Link>

            {/* Mobile Hamburger Toggle */}
            <button
              className={`hamburger-btn ${isOpen ? 'active' : ''}`}
              onClick={() => setIsOpen(!isOpen)}
              aria-label="Menu"
            >
              <span className="line" />
              <span className="line" />
            </button>
          </div>
        </div>
      </header>

      {/* Mobile Drawer Menu */}
      <div className={`mobile-drawer ${isOpen ? 'drawer-open' : ''}`}>
        <div className="drawer-inner">
          <div className="drawer-header">
            <span className="drawer-tag">NAVIGATION</span>
            <button className="drawer-close-btn" onClick={() => setIsOpen(false)}>✕</button>
          </div>

          <div className="drawer-links">
            {navLinks.map((link, i) => (
              <Link
                key={link.label}
                href={link.href}
                className="drawer-link"
                onClick={() => setIsOpen(false)}
              >
                <span className="drawer-link-num">0{i + 1}</span>
                <span className="drawer-link-text">{link.label}</span>
              </Link>
            ))}
          </div>

          <div className="drawer-footer">
            <Link
              href="/#diagnostic"
              className="drawer-cta"
              onClick={() => setIsOpen(false)}
            >
              <span>Réserver mon Diagnostic Gratuit</span>
              <span>→</span>
            </Link>
            <div className="drawer-sig">
              <strong>Marie Sylvanus KINKPON</strong>
              <span>AUTOMATISATION · IA · SOLUTIONS</span>
            </div>
          </div>
        </div>
      </div>

      <style jsx>{`
        .nav-wrapper {
          position: fixed;
          top: 0;
          left: 0;
          width: 100%;
          z-index: 1000;
          padding: 1.25rem 2rem;
          transition: all 0.35s ease;
        }

        .nav-wrapper.is-scrolled {
          padding: 0.75rem 2rem;
        }

        .nav-container {
          max-width: 1300px;
          margin: 0 auto;
          background: rgba(255, 255, 255, 0.85);
          backdrop-filter: blur(16px);
          -webkit-backdrop-filter: blur(16px);
          border: 1px solid rgba(234, 228, 218, 0.8);
          border-radius: 999px;
          padding: 0.6rem 1.4rem;
          display: flex;
          align-items: center;
          justify-content: space-between;
          box-shadow: 0 8px 24px rgba(9, 30, 58, 0.05);
          transition: all 0.3s ease;
        }

        .nav-wrapper.is-scrolled .nav-container {
          background: rgba(255, 255, 255, 0.95);
          box-shadow: 0 12px 30px rgba(9, 30, 58, 0.08);
          border-color: #E2DBD0;
        }

        /* Logo */
        .nav-logo {
          display: flex;
          align-items: center;
          gap: 0.75rem;
          text-decoration: none;
        }

        .logo-icon {
          width: 36px;
          height: 36px;
          background: var(--color-navy, #091E3A);
          color: #ffffff;
          border-radius: 50%;
          display: flex;
          align-items: center;
          justify-content: center;
          font-family: var(--font-display, sans-serif);
          font-weight: 800;
          font-size: 1rem;
        }

        .logo-text {
          display: flex;
          flex-direction: column;
        }

        .logo-text .name {
          font-family: var(--font-display, sans-serif);
          font-weight: 800;
          font-size: 0.95rem;
          color: var(--color-navy, #091E3A);
          letter-spacing: -0.01em;
          line-height: 1.1;
        }

        .logo-text .role {
          font-size: 0.62rem;
          font-weight: 700;
          color: var(--color-turquoise, #00A896);
          letter-spacing: 0.12em;
        }

        /* Desktop Nav */
        .desktop-links {
          display: flex;
          align-items: center;
          gap: 2rem;
        }

        .nav-item {
          font-size: 0.88rem;
          font-weight: 600;
          color: var(--color-navy, #091E3A);
          opacity: 0.8;
          transition: all 0.25s ease;
          position: relative;
          padding: 0.2rem 0;
        }

        .nav-item:hover {
          opacity: 1;
          color: var(--color-turquoise, #00A896);
        }

        /* CTA Button */
        .nav-actions {
          display: flex;
          align-items: center;
          gap: 1rem;
        }

        .cta-diagnostic-btn {
          display: inline-flex;
          align-items: center;
          gap: 0.6rem;
          background: var(--color-orange, #FF6B35);
          color: #ffffff;
          font-size: 0.82rem;
          font-weight: 700;
          padding: 0.6rem 1.25rem;
          border-radius: 999px;
          text-decoration: none;
          box-shadow: 0 4px 14px rgba(255, 107, 53, 0.35);
          transition: all 0.3s cubic-bezier(0.16, 1, 0.3, 1);
        }

        .cta-diagnostic-btn:hover {
          background: var(--color-orange-hover, #F2571D);
          transform: translateY(-2px);
          box-shadow: 0 6px 20px rgba(255, 107, 53, 0.45);
        }

        .cta-dot {
          width: 7px;
          height: 7px;
          border-radius: 50%;
          background: #ffffff;
          animation: pulse 1.6s infinite;
        }

        @keyframes pulse {
          0%, 100% { opacity: 1; transform: scale(1); }
          50% { opacity: 0.4; transform: scale(0.75); }
        }

        /* Hamburger */
        .hamburger-btn {
          display: none;
          flex-direction: column;
          gap: 5px;
          background: none;
          border: none;
          cursor: pointer;
          padding: 0.5rem;
        }

        .hamburger-btn .line {
          width: 22px;
          height: 2px;
          background: var(--color-navy, #091E3A);
          transition: all 0.3s ease;
        }

        .hamburger-btn.active .line:nth-child(1) {
          transform: translateY(3.5px) rotate(45deg);
        }

        .hamburger-btn.active .line:nth-child(2) {
          transform: translateY(-3.5px) rotate(-45deg);
        }

        /* Mobile Drawer */
        .mobile-drawer {
          position: fixed;
          top: 0;
          left: 0;
          width: 100%;
          height: 100vh;
          background: rgba(9, 30, 58, 0.5);
          backdrop-filter: blur(8px);
          z-index: 1100;
          opacity: 0;
          pointer-events: none;
          transition: opacity 0.3s ease;
        }

        .mobile-drawer.drawer-open {
          opacity: 1;
          pointer-events: auto;
        }

        .drawer-inner {
          position: absolute;
          top: 0;
          right: 0;
          width: 85%;
          max-width: 380px;
          height: 100%;
          background: #FAF8F5;
          padding: 2rem;
          display: flex;
          flex-direction: column;
          justify-content: space-between;
          transform: translateX(100%);
          transition: transform 0.4s cubic-bezier(0.16, 1, 0.3, 1);
          box-shadow: -10px 0 30px rgba(0,0,0,0.1);
        }

        .mobile-drawer.drawer-open .drawer-inner {
          transform: translateX(0);
        }

        .drawer-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding-bottom: 1.5rem;
          border-bottom: 1px solid #EAE4DA;
        }

        .drawer-tag {
          font-size: 0.7rem;
          font-weight: 700;
          letter-spacing: 0.15em;
          color: #8798AD;
        }

        .drawer-close-btn {
          background: none;
          border: none;
          font-size: 1.2rem;
          color: #091E3A;
          cursor: pointer;
        }

        .drawer-links {
          display: flex;
          flex-direction: column;
          gap: 1.25rem;
          margin-top: 2rem;
        }

        .drawer-link {
          display: flex;
          align-items: center;
          gap: 1rem;
          font-size: 1.2rem;
          font-weight: 700;
          color: #091E3A;
          text-decoration: none;
          padding: 0.5rem 0;
          border-bottom: 1px solid rgba(234, 228, 218, 0.5);
        }

        .drawer-link-num {
          font-size: 0.8rem;
          color: #00A896;
        }

        .drawer-footer {
          display: flex;
          flex-direction: column;
          gap: 1.5rem;
        }

        .drawer-cta {
          display: flex;
          align-items: center;
          justify-content: space-between;
          background: #FF6B35;
          color: #ffffff;
          font-weight: 700;
          font-size: 0.9rem;
          padding: 1rem 1.4rem;
          border-radius: 14px;
          text-decoration: none;
        }

        .drawer-sig {
          display: flex;
          flex-direction: column;
          font-size: 0.75rem;
          color: #54667D;
        }

        .drawer-sig strong {
          color: #091E3A;
        }

        @media (max-width: 900px) {
          .desktop-links {
            display: none;
          }
          .hamburger-btn {
            display: flex;
          }
          .nav-wrapper {
            padding: 1rem;
          }
          .cta-diagnostic-btn {
            display: none;
          }
        }
      `}</style>
    </>
  );
}

// src/layouts/NavBar.vue
<script setup>
import { Braces, HomeIcon, InfoIcon, Phone, Menu, X, Sparkles } from 'lucide-vue-next';
import { ref, onMounted, watch } from 'vue';
import gsap from 'gsap';

const isMenuOpen = ref(false);
const isScrolled = ref(false);

// Observer le défilement pour changer le style de la navbar
onMounted(() => {
  window.addEventListener('scroll', () => {
    isScrolled.value = window.scrollY > 10;
  });

  // Animation d'entrée de la navbar
  const tl = gsap.timeline();
  
  tl.fromTo(".logo-letter", 
    { y: -20, opacity: 0 },
    { y: 0, opacity: 1, duration: 0.6, stagger: 0.05, ease: "back.out(1.7)" }
  )
  .fromTo(".nav-name", 
    { y: -15, opacity: 0 },
    { y: 0, opacity: 1, duration: 0.5 },
    "-=0.3"
  )
  .fromTo(".nav-title", 
    { y: -10, opacity: 0 },
    { y: 0, opacity: 1, duration: 0.4, stagger: 0.1 },
    "-=0.2"
  )
  .fromTo(".nav-item", 
    { y: -10, opacity: 0 },
    { y: 0, opacity: 1, duration: 0.5, stagger: 0.1 },
    "-=0.3"
  );

  // Animation des séparateurs
  gsap.fromTo(".nav-separator",
    { scaleX: 0, opacity: 0 },
    { scaleX: 1, opacity: 1, duration: 0.8, delay: 0.5, ease: "power2.out" }
  );
});

// Observer l'état du menu mobile pour l'animation
watch(isMenuOpen, (newVal) => {
  if (newVal) {
    // Ouvrir le menu mobile avec animation
    gsap.to(".mobile-menu", {
      y: 0,
      opacity: 1,
      duration: 0.4,
      ease: "power2.out"
    });
    
    gsap.fromTo(".mobile-nav-item",
      { x: -20, opacity: 0 },
      { x: 0, opacity: 1, duration: 0.4, stagger: 0.1 }
    );
  } else {
    // Fermer le menu mobile avec animation
    gsap.to(".mobile-menu", {
      y: -10,
      opacity: 0,
      duration: 0.3,
      ease: "power2.in"
    });
  }
});

// Animation des liens au survol
const animateNavItem = (element, isHover) => {
  if (isHover) {
    gsap.to(element, {
      y: -3,
      scale: 1.05,
      duration: 0.3,
      ease: "power2.out"
    });
    
    gsap.to(element.querySelector('svg'), {
      rotation: 10,
      duration: 0.3,
      ease: "power2.out"
    });
  } else {
    gsap.to(element, {
      y: 0,
      scale: 1,
      duration: 0.3,
      ease: "power2.out"
    });
    
    gsap.to(element.querySelector('svg'), {
      rotation: 0,
      duration: 0.3,
      ease: "power2.out"
    });
  }
};
</script>

<template>
  <nav 
    class="w-full py-4 fixed top-0 z-50 transition-all duration-300"
    :class="isScrolled ? 'bg-white/90 backdrop-blur-md shadow-lg' : 'bg-[#E9E1D1] shadow-sm'"
  >
    <div class="flex justify-between items-center max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <!-- Logo PORTFOLIO avec animation -->
      <div class="flex font-bold text-lg sm:text-xl text-neutral-800 tracking-widest">
        <span 
          v-for="(letter, index) in 'PORTFOLIO'" 
          :key="index" 
          class="logo-letter inline-block"
        >
          {{ letter }}
        </span>
      </div>

      <div class="nav-separator h-6 w-px bg-neutral-300 mx-2 md:mx-4"></div>
      
      <!-- Nom et titre - visible à partir de md -->
      <div class="text-center flex-shrink-0 hidden md:block mx-2">
        <p class="nav-name font-semibold text-base lg:text-lg text-neutral-800 tracking-wide m-0">MARIE SYLVANUS KINKPON</p>
        <p class="nav-title text-xs lg:text-sm text-gray-500 italic mt-1 m-0">Développeur full-stack</p>
        <p class="nav-title text-xs lg:text-sm text-gray-500 italic mt-1 m-0">...de l'idée au résultat</p>
      </div>

      <div class="nav-separator h-6 w-px bg-neutral-300 mx-2 md:mx-4"></div>
      
      <!-- Menu de navigation desktop -->
      <div class="hidden md:flex gap-4 lg:gap-6">
        <router-link 
          to="/" 
          class="nav-item flex flex-col items-center no-underline text-neutral-700 transition-all duration-300 p-2 rounded-lg hover:text-white hover:bg-neutral-600 group relative"
          title="Accueil"
          @mouseenter="e => animateNavItem(e.currentTarget, true)"
          @mouseleave="e => animateNavItem(e.currentTarget, false)"
        >
          <HomeIcon class="w-5 h-5 lg:w-6 lg:h-6 mb-1 transition-transform" />
          <span class="text-xs font-medium">Accueil</span>
          <Sparkles class="absolute -top-1 -right-1 w-3 h-3 text-yellow-500 opacity-0 group-hover:opacity-100 transition-opacity" />
        </router-link>
        <router-link 
          to="/about" 
          class="nav-item flex flex-col items-center no-underline text-neutral-700 transition-all duration-300 p-2 rounded-lg hover:text-white hover:bg-neutral-600 group relative"
          title="À propos"
          @mouseenter="e => animateNavItem(e.currentTarget, true)"
          @mouseleave="e => animateNavItem(e.currentTarget, false)"
        >
          <InfoIcon class="w-5 h-5 lg:w-6 lg:h-6 mb-1 transition-transform" />
          <span class="text-xs font-medium">À propos</span>
          <Sparkles class="absolute -top-1 -right-1 w-3 h-3 text-yellow-500 opacity-0 group-hover:opacity-100 transition-opacity" />
        </router-link>
        <router-link 
          to="/projets" 
          class="nav-item flex flex-col items-center no-underline text-neutral-700 transition-all duration-300 p-2 rounded-lg hover:text-white hover:bg-neutral-600 group relative"
          title="Projets"
          @mouseenter="e => animateNavItem(e.currentTarget, true)"
          @mouseleave="e => animateNavItem(e.currentTarget, false)"
        >
          <Braces class="w-5 h-5 lg:w-6 lg:h-6 mb-1 transition-transform" />
          <span class="text-xs font-medium">Projets</span>
          <Sparkles class="absolute -top-1 -right-1 w-3 h-3 text-yellow-500 opacity-0 group-hover:opacity-100 transition-opacity" />
        </router-link>
        <router-link 
          to="/contact" 
          class="nav-item flex flex-col items-center no-underline text-neutral-700 transition-all duration-300 p-2 rounded-lg hover:text-white hover:bg-neutral-600 group relative"
          title="Contact"
          @mouseenter="e => animateNavItem(e.currentTarget, true)"
          @mouseleave="e => animateNavItem(e.currentTarget, false)"
        >
          <Phone class="w-5 h-5 lg:w-6 lg:h-6 mb-1 transition-transform" />
          <span class="text-xs font-medium">Contact</span>
          <Sparkles class="absolute -top-1 -right-1 w-3 h-3 text-yellow-500 opacity-0 group-hover:opacity-100 transition-opacity" />
        </router-link>
      </div>

      <!-- Bouton menu mobile -->
      <button 
        @click="isMenuOpen = !isMenuOpen"
        class="md:hidden p-2 rounded-lg text-neutral-700 hover:bg-neutral-100 transition-colors relative"
        aria-label="Menu"
        :class="isMenuOpen ? 'bg-neutral-100' : ''"
      >
        <Menu v-if="!isMenuOpen" class="w-6 h-6 transition-transform" :class="isMenuOpen ? 'rotate-90' : ''" />
        <X v-else class="w-6 h-6 transition-transform" :class="isMenuOpen ? 'rotate-90' : ''" />
        
        <!-- Indicateur animé -->
        <span v-if="isMenuOpen" class="absolute -top-1 -right-1 w-3 h-3 bg-green-500 rounded-full animate-ping"></span>
        <span v-if="isMenuOpen" class="absolute -top-1 -right-1 w-3 h-3 bg-green-500 rounded-full"></span>
      </button>
    </div>

    <!-- Menu mobile -->
    <div 
      v-if="isMenuOpen"
      class="mobile-menu md:hidden absolute top-full left-0 right-0 bg-white/95 backdrop-blur-md shadow-lg z-50 border-t border-neutral-200 transform -translate-y-2 opacity-0"
    >
      <div class="px-4 py-4 space-y-2">
        <router-link 
          to="/" 
          @click="isMenuOpen = false"
          class="mobile-nav-item flex items-center no-underline text-neutral-700 transition-all duration-300 p-3 rounded-lg hover:text-white hover:bg-neutral-600"
          title="Accueil"
        >
          <HomeIcon class="w-5 h-5 mr-3" />
          <span class="font-medium">Accueil</span>
        </router-link>
        <router-link 
          to="/about" 
          @click="isMenuOpen = false"
          class="mobile-nav-item flex items-center no-underline text-neutral-700 transition-all duration-300 p-3 rounded-lg hover:text-white hover:bg-neutral-600"
          title="À propos"
        >
          <InfoIcon class="w-5 h-5 mr-3" />
          <span class="font-medium">À propos</span>
        </router-link>
        <router-link 
          to="/projets" 
          @click="isMenuOpen = false"
          class="mobile-nav-item flex items-center no-underline text-neutral-700 transition-all duration-300 p-3 rounded-lg hover:text-white hover:bg-neutral-600"
          title="Projets"
        >
          <Braces class="w-5 h-5 mr-3" />
          <span class="font-medium">Projets</span>
        </router-link>
        <router-link 
          to="/contact" 
          @click="isMenuOpen = false"
          class="mobile-nav-item flex items-center no-underline text-neutral-700 transition-all duration-300 p-3 rounded-lg hover:text-white hover:bg-neutral-600"
          title="Contact"
        >
          <Phone class="w-5 h-5 mr-3" />
          <span class="font-medium">Contact</span>
        </router-link>
      </div>
    </div>
  </nav>

  <!-- Espace pour la navbar fixe -->
  <div class="h-20"></div>
</template>

<style scoped>
.logo-letter {
  opacity: 0;
  transform: translateY(-20px);
}

.nav-name, .nav-title, .nav-item {
  opacity: 0;
  transform: translateY(-10px);
}

.nav-separator {
  opacity: 0;
  transform: scaleX(0);
}

.mobile-nav-item {
  opacity: 0;
  transform: translateX(-20px);
}

/* Animation pour l'indicateur de page active */
.router-link-active {
  background-color: #374151;
  color: white;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}

.router-link-active:hover {
  background-color: #4B5563;
}

/* Animation pour le bouton menu mobile */
button {
  transition: all 0.3s ease;
}

/* Responsive pour très petits écrans */
@media (max-width: 480px) {
  .flex > div:first-child {
    font-size: 0.9rem;
  }
  
  .max-w-7xl {
    padding-left: 1rem;
    padding-right: 1rem;
  }
}

/* Effet de transition douce pour la navbar */
nav {
  transition: background-color 0.3s ease, box-shadow 0.3s ease, backdrop-filter 0.3s ease;
}

/* Amélioration de l'accessibilité */
button:focus {
  outline: 2px solid #8B5CF6;
  outline-offset: 2px;
}

/* Animation pour les séparateurs */
.nav-separator {
  transform-origin: center center;
}
</style>
